/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const TradeOutcome = IDL.Variant({
  'win' : IDL.Null,
  'loss' : IDL.Null,
});
export const Trade = IDL.Record({
  'profitOrLoss' : IDL.Float64,
  'invest' : IDL.Float64,
  'timestamp' : Time,
  'outcome' : TradeOutcome,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTradingData' : IDL.Func(
      [],
      [
        IDL.Record({
          'trades' : IDL.Vec(Trade),
          'totalLoss' : IDL.Float64,
          'totalProfit' : IDL.Float64,
          'target' : IDL.Float64,
          'capital' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordTrade' : IDL.Func([IDL.Float64, TradeOutcome], [], []),
  'resetTradingData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCapital' : IDL.Func([IDL.Float64], [], []),
  'setTargetProfit' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const TradeOutcome = IDL.Variant({ 'win' : IDL.Null, 'loss' : IDL.Null });
  const Trade = IDL.Record({
    'profitOrLoss' : IDL.Float64,
    'invest' : IDL.Float64,
    'timestamp' : Time,
    'outcome' : TradeOutcome,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTradingData' : IDL.Func(
        [],
        [
          IDL.Record({
            'trades' : IDL.Vec(Trade),
            'totalLoss' : IDL.Float64,
            'totalProfit' : IDL.Float64,
            'target' : IDL.Float64,
            'capital' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordTrade' : IDL.Func([IDL.Float64, TradeOutcome], [], []),
    'resetTradingData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCapital' : IDL.Func([IDL.Float64], [], []),
    'setTargetProfit' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };